env:
  node: true
  es6: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:prettier/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2018
  project: "./tsconfig.eslint.json"
rules:

  # these are related to using any
  "@typescript-eslint/no-unsafe-member-access": "off"
  "@typescript-eslint/no-unsafe-assignment": "off"
  "@typescript-eslint/restrict-template-expressions": "off"
  "@typescript-eslint/explicit-module-boundary-types": "off"
  "@typescript-eslint/no-explicit-any": "off"

  no-undef: "off"
  no-unused-vars: "off"
  no-constant-condition: "off"
  "@typescript-eslint/type-annotation-spacing":
    - error
    - before: false
      after: true
      overrides:
        arrow:
          before: true
          after: true
  "@typescript-eslint/no-unused-vars":
    - error
    - args: none
  "@typescript-eslint/no-unused-expressions": error
  prefer-arrow-callback:
    - error
    - allowUnboundThis: false
  "@typescript-eslint/no-empty-function": "off"
  "@typescript-eslint/no-misused-promises":
    - error
    - checksVoidReturn: false
  curly: error
  eol-last: error
  no-caller: error
  no-multiple-empty-lines: error
  no-new-wrappers: error
  no-eval: error
  no-invalid-this: error
  no-console: "off"
  "@typescript-eslint/no-require-imports": error
  no-shadow: error
  no-trailing-spaces: error
  no-empty:
    - error
    - allowEmptyCatch: true
  no-unused-expressions: "off"
  no-var: error
  object-shorthand: error
  one-var:
    - error
    - initialized: never
      uninitialized: never
  prefer-const: error
  "@typescript-eslint/semi":
    - error
    - never
  "@typescript-eslint/member-delimiter-style":
    - error
    - multiline:
        delimiter: comma
        requireLast: false
      singleline:
        delimiter: comma
        requireLast: false
  default-case: error
  eqeqeq:
    - error
    - always
  space-before-function-paren:
    - error
    - anonymous: always
      named: never
      asyncArrow: always
  func-call-spacing:
    - error
    - never
  no-multi-spaces:
    - error
    - ignoreEOLComments: true
  # align:
  # - true
  # - parameters
  # - statements
  # no-angle-bracket-type-assertion: true
  # no-default-export: true
  # one-line:
  # - true
  # - check-catch
  # - check-else
  # - check-finally
  # - check-open-brace
  # - check-whitespace
  # typedef-whitespace:
  # - true
  # - call-signature: onespace
  #   index-signature: nospace
  #   parameter: nospace
  #   property-declaration: nospace
  #   variable-declaration: nospace
  # - call-signature: onespace
  #   index-signature: onespace
  #   parameter: onespace
  #   property-declaration: onespace
  #   variable-declaration: onespace
  # whitespace:
  # - true
  # - check-branch
  # - check-decl
  # - check-operator
  # - check-separator
  # - check-type
  # - check-typecast
overrides:
  - files:
      - viewer/**/*.ts
    extends:
      - plugin:import/errors
      - plugin:import/warnings
    parserOptions:
      ecmaVersion: 2018
      project: "./tsconfig.eslint.viewer.json"
    rules:
      "@typescript-eslint/interface-name-prefix":
        - error
        - prefixWithI: always
      "@typescript-eslint/no-unnecessary-type-assertion": "off"
      import/no-unresolved: "off"
      import/extensions:
        - error
        - always
