# see https://github.com/sdras/awesome-actions for a good list of available action
name: Github-CI

on:
  push:
    branches: [master, ci-*]
  pull_request:
    branches: [master]

jobs:

  build:

    name: "${{ matrix.os }}/Node-${{matrix.node-version}}"
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [10.x]  # [8.x, 10.x]
        # code-version: [stable, insiders]
        include:
        - os: ubuntu-latest
          node-version: 12.x
        - os: ubuntu-latest
          node-version: 14.x

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Compile
      run: |
        npm ci
        npm run compile
    - name: Lint Code
      run: npm run lint
    - name: Build Grammar
      run: npm run build
      # TODO test built files don't change after this?
    - name: Run tests
      uses: GabrielBB/xvfb-action@v1.0
      with:
        run: npm test

  publish:
    # only if all tests complete and the commit is tagged as a release
    name: Publish to Marketplace
    needs: build
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') && contains(github.ref, 'release')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - uses: lannonbr/vsce-action@master
      with:
        args: "publish -p $VSCE_TOKEN"
      env:
        VSCE_TOKEN: ${{ secrets.VSCE_PUB }}