name: Github-CI

on: [push, pull_request]

jobs:

  build:

    name: "${{ matrix.os }}/${{matrix.node-version}}/${{ matrix.code-version }}"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        # node-version: [8.x, 10.x]
        include:
          - code-version: stable
            node-version: 8.x
          - code-version: insiders
            node-version: 10.x

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Compile
      run: |
        npm ci
        npm run compile
    - name: Lint Code
      run: npm run lint
    - name: Build Grammar
      run: npm run build
      # TODO test built files don't change after this?
    - name: Run tests
      uses: GabrielBB/xvfb-action@v1.0
      with:
        run: npm test

  publish:
    # only if all tests complete and the commit is tagged as a release
    name: Publish to Marketplace
    needs: build
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') && contains(github.ref, 'release')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 8.x
      uses: actions/setup-node@v1
      with:
        node-version: 8.x
    - name: Compile
      run: npm ci
    - name: Publish
      run: vsce publish -p $VSCE_TOKEN
      env:
        VSCE_TOKEN: ${{ secrets.VSCE_PUB }}